baseURL = "https://fuzqing.com"
languageCode = "zh-CN"
title = "Fuzqing's Blog"
theme = "maupassant"

[author]
  name = "Fuzqing"

[params]
  author = "Fuzqing"
  subtitle = "做人如果没有梦想，那和咸鱼有什么分别？你连废物都不如，你应该叫狗贼。"
  keywords = "PHP,Swoole,Golang,Go语言,Web开发"
  description = "记录工作、学习中遇到的问题和解决方法..."
  busuanzi = true

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about"
    weight = 3

[[params.links]]
  title = "MIKELIN | 关注科技，弘扬互联网精神！"
  name = "MIKELIN"
  url = "https://mikelin.cn"

[[params.links]]
  title = "黄伟桐的网络日志"
  name = "黄伟桐的网络日志"
  url = "https://huangweitong.com"

[params.utteranc]
    enable = true
    repo = "fuzqing/blog"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
